// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "cscs"
#define SECRET_PASS ""

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a29kxzq7fheoki-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICpjCCAY6gAwIBAgIVAKDRKD6FGHLMIGfW8xsd8YStNbPFMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0xOTEyMTMwOTI3
NDJaFw00OTEyMzEyMzU5NTlaMDUxFjAUBgNVBAYTDU15TUtSV2lGaTEwMTAxGzAZ
BgNVBAMTEjAxMjM2QTU1Q0Q0ODNEMUJFRTBZMBMGByqGSM49AgEGCCqGSM49AwEH
A0IABA/myv77khe8XWq1P9FaKPU1vf3kwK7lLGCnPrJOz//MXkWK2LGdtmAkvUEd
GGEkKlG7MvZsmbDAuTSvB6Mkt/6jYDBeMB8GA1UdIwQYMBaAFN0MWN0GDl8vu5D5
m1fOUq02krK2MB0GA1UdDgQWBBQQLPRzZRC41ZEGo5oL2OqidcvnYjAMBgNVHRMB
Af8EAjAAMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEAiL4n7mRn 
Al9LfbdGFZwF4RgPaau1HSxi8P/j03ZM3uKqZcakstXhwpogU5NEp9GLH1CNc+zs
Mpg5ctK+hKYf6DSVVjTODUxDs9Qtqz/Vv5W53MAS+XeyD4hiMDW+ap5LKefZTv49
Gc1RAoHDcedcenDuZjYvRAGjFZmwTxj9wGWJNYMzdlOSDUxgHsfSi3xza87SLE+O
Rot+cjCKU/pIKHysJEgqWHI2rG/kWv68RVGWhr5lXS+FT+eJmAqiHJMa27ZvMRzD
G+OiCpEijBVOWyDeKvi1UK9gS7x9dB8fSE3FOup6RTRjlBoUXebGb0w0YVKPnKUM
fkDFTdEwW01LCw==
-----END CERTIFICATE-----
)";
